### ISSUE TITLE
3d Party NFT Marketplace Buttons/Links

### ISSUE THREAD

**Issue by ramseynasr** [rise-of-the-warbots/support#3]
How that our Amorphous Warbots are being deployed to marketplaces like OpenSea or LootEx, etc, can we please add links or buttons to those marketplaces under the main Warbot webiste/marketplace page? 

This would be very helpful for our community to be able to go from our home base directly to their marketplace of choice to review their collections, etc.

Thank you!

**Comment by xyrus02** [comment]
Scheduled for deployment
