### ISSUE TITLE
Unstake not working

### ISSUE THREAD

**Issue by Zerose7en** [rise-of-the-warbots/support#6]
Having issues unstaking 1 mmac. I had accidentally only staked for 1 period. I keep getting Json-rpc error when clicking unstake button.

![Screenshot_20211212-190852_MetaMask](https://user-images.githubusercontent.com/95995503/145702350-662d463b-73ef-4e06-92fc-0406552ce3d1.jpg)
![Screenshot_20211212-190901_MetaMask](https://user-images.githubusercontent.com/95995503/145702352-4f2658ec-c7b2-4f0f-a7e2-20b216e0f99d.jpg)

**Comment by xyrus02** [comment]
Thanks for reporting. The issue is in the backend and we will update the contract.
This will go transparent for you - once done, you will be simply able to unstake from the website.

**Comment by xyrus02** [comment]
Scheduled for deployment
